services:
  nexadash:
    image: jamiechalmerzlp/nexadash:latest
    container_name: nexadash
    restart: unless-stopped
    privileged: true
    ports:
      - "3001:3001"
    environment:
      NEXADASH_SHOW_HOST: "true"
      NEXADASH_ENABLE_CPU_TEMPS: "true"
    volumes:
      - type: bind
        source: /
        target: /mnt/host
        read_only: true
