# !! Attention !!
# This is a docker-compose file used ONLY for the dev environment and can not be used for production.
# If you need instructions on how to run NexaDash, please have a look at the README.md file in the root of the project.
services:
  nexadash:
    # image: jamiechalmerzlp/nexadash:dev
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    tty: true
    restart: unless-stopped
    privileged: true
    environment:
      - NEXADASH_ENABLE_CPU_TEMPS=true
      - NEXADASH_SHOW_NEXADASH_VERSION=none
    expose:
      - 3001
    volumes:
      - /:/mnt/host:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexadash.rule=Host(`nexadash-dev.local`)" # for this to work, you will have to add an entry to /etc/hosts

  traefik:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
